### ISSUE TITLE
error_shape mismatch while fitting model

### ISSUE THREAD

**Issue by as4401s** [nikhilroxtomar/UNet-Segmentation-in-Keras-TensorFlow#1]
Did you run into any such errors?

ValueError: A target array with shape (8, 512, 512, 3) was passed for an output of shape (None, 512, 512, 1) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.

**Comment by nikhilroxtomar** [comment]
I think you are working on multi class segmentation, but this code only works for binary segmentation.

**Comment by as4401s** [comment]
Hi. Thanks for the reply. I figured it out. The segmented image I was using had 3 channels instead of one. That was causing the problem.
